# Generated by Django 5.2.8 on 2026-01-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('age', models.IntegerField(max_length=3)),
                ('course', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='userProfile/')),
            ],
        ),
    ]
